name: R-CMD-CHECK

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  R-CMD-CHECK:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/philchalmers/container-mirt:latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: R CMD CHECK
        run: |
          Rscript -e 'install.packages(c("latticeExtra", "directlabels", "Rsolnp", "nloptr", "plink", "mirtCAT")); devtools::check(error_on = "warning")'
